#!/usr/bin/env node
"use strict";

var argv = require("yargs")
  .strict()
  .usage("Deletes all indexes.")
  .help('help')
  .argv;

var elasticsearch = require('elasticsearch');
var config = require('../config');
var client = new elasticsearch.Client(config);

client.indices.delete({
  index: ["*"],
  ignore: [404]
}, function(error, resp) {
  if (error) {
    console.error("Could not delete indexes:", error, resp);
  }
  client.close();
});
