#!/usr/bin/env node

var argv = require("yargs")
  .strict()
  .usage("Usage: converter -i [<input-file-or-URL>] -o output.json", {
    i: {
        describe: 'specify input file',
        alias: ('i','input')
    },
    pretty: {
      describe: 'create pretty json'
    }
  })
  .demand(['i'])
  .argv;

var fs = require('fs');
var path = require('path');
var request = require('request');
var convert = require('../src/convert');

function save(article) {
  var outFile = path.join(__dirname, "..", "data", "json", article.id + ".json");
  console.info("Writing file", outFile);
  var data;
  if (argv.pretty) {
    data = JSON.stringify(article.toJSON(), null, 2);
  } else {
    data = JSON.stringify(article.toJSON());
  }
  fs.writeFileSync(outFile, data);
}

if (/^http.:/.exec(argv.i)) {
  var url = argv.i;
  request(url, function (error, response, body) {
    if (error || response.statusCode != 200) {
      console.error("Could not load data from URL", url);
    } else {
      var xmlData = body;
      save(convert(xmlData));
    }
  });
} else {
  var inputFile = path.join(__dirname, "..", argv.i);
  if (!fs.existsSync(inputFile)) {
    console.error("Input file not found.");
  } else {
    var xmlData = fs.readFileSync(inputFile, 'utf8');
    save(convert(xmlData));
  }
}
