#!/usr/bin/env node

var request = require('request');
var convert = require('../src/convert');
var listOfUrls = require('../data/filelist');
var elasticsearch = require('elasticsearch');
var config = require('../config');
var indexArticle = require('../src/index_article');

var client = new elasticsearch.Client(config);

var idx = 0;
var count = 0;
var MAX_COUNT = -1;

function step() {
  if (idx >= listOfUrls.length || (MAX_COUNT > 0 && count >= MAX_COUNT)) {
    console.error("Done.");
    client.close();
    return;
  }

  var url = listOfUrls[idx++];
  console.log("Processing %s...", url);
  request(url, function (error, response, body) {

    if (url === "https://s3.amazonaws.com/elife-cdn/elife-articles/00808/elife00808.xml") {
      console.error("skipping problematic article 00808");
      step();
    } else if (error || response.statusCode != 200) {
      console.error("... could not load data.");
      step();
    } else {



      var xmlData = body;
      console.info("... converting");
      var article = convert(xmlData);
      console.info("... indexing");
      indexArticle(client, article)
      .error(function() {
        console.info("... failed.");
        step();
      })
      .done(function() {
        console.info("... done.");
        count++;
        step();
      });
    }
  });
}

console.info('Clearing indexes...');
client.indices.delete({
  index: ["*"],
  ignore: [404]
}).then(function() {
  console.info('Initializing index...');
  return client.indices.create({
    'index': 'articles',
    'body': {
      "settings": {
        "analysis": {
          "filter": {
            "trigrams_filter": {
              "type": "ngram",
              "min_gram": 3,
              "max_gram": 3
            }
          },
          "analyzer": {
            "html_content": {
              "type":      "custom",
              "tokenizer": "standard",
              "char_filter": [ "html_strip" ],
              "filter":   [ "classic" ]
            }
          }
        }
      },
      "mappings": {
        "article": {
         "properties": {
           // title and intro are indexed for fuzzy full-text search
           "title": { "type": "string", "index" : "analyzed", "analyzer": "html_content", "search_analyzer": 'snowball', "language": "English" },
           "intro": { "type": "string", "index" : "analyzed", "analyzer": "html_content", "search_analyzer": 'snowball', "language": "English" },
           // authors for exact full-text search (no partial matches)
           // "authors": { "type": "string", "index" : "analyzed", "analyzer": "standard" },
           "authors": { "type": "string", "index" : "not_analyzed"},
           // The rest are facets which are used for strict match queries or filtering only
           "published_on": { "type": "string", "index" : "not_analyzed"},
           "article_type": { "type": "string", "index" : "not_analyzed"},
           "subjects": { "type": "string", "index" : "not_analyzed"},
           "organisms": { "type": "string", "index" : "not_analyzed"}
         }
        },
        "fragment": {
          "_parent": {"type": "article"},
          "properties": {
            "id": { "type": "string", "index" : "not_analyzed" },
            "type": { "type": "string", "index" : "not_analyzed" },
            "content": { "type": "string", "index" : "analyzed", "analyzer": "html_content", "search_analyzer": 'snowball', "language": "English" },
            "position": { "type": "integer", "index": "not_analyzed" }
          }
        }
      }
    }
  });
}).error(function(error, resp) {
  console.error("Client error:", error, resp);
  client.close();
})
.done(function() {
  step();
});
