#!/usr/bin/env node

var request = require('request');
var convert = require('../src/convert');
var listOfUrls = require('../data/filelist');
var elasticsearch = require('elasticsearch');
var getConfig = require('./get_config');
var indexArticle = require('../src/index_article.js');

var client = new elasticsearch.Client(getConfig());

var idx = 0;
var count = 0;
var MAX_COUNT = 10;
var MAX_TRIES = 20;

function step() {
  if (idx >= MAX_TRIES) {
    console.error("Stopping: exceeding maximum number of tries.");
    client.close();
    return;
  } else if (count >= MAX_COUNT) {
    console.info("Finished successfully.");
    client.close();
    return;
  }

  var url = listOfUrls[idx++];
  console.log("Processing %s...", url);
  request(url, function (error, response, body) {

    if (error || response.statusCode != 200) {
      console.error("... could not load data.");
      step();
    } else {
      var xmlData = body;
      console.info("... converting");
      var article = convert(xmlData);
      console.info("... indexing");
      indexArticle(client, article)
      .error(function() {
        console.info("... failed.");
        step();
      })
      .done(function() {
        console.info("... done.");
        count++;
        step();
      });
    }
  });
}

client.indices.delete({
  index: ["articles", "content"],
  ignore: [404]
}, function(error, resp) {
  if (error) {
    console.error("Client error:", error, resp);
    client.close();
  } else {
    step();
  }
});
